# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:
  psql:
    image: postgres:17-alpine
    environment:
      - "POSTGRES_DB=developer"
      - "POSTGRES_USER=developer"
      - "POSTGRES_PASSWORD=developer"
    ports:
      - "5432:5432"
