# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:
  psql:
    image: postgres:17-alpine
    environment:
      - "POSTGRES_DB=developer"
      - "POSTGRES_USER=developer"
      - "POSTGRES_PASSWORD=developer"
    ports:
      - "5432:5432"
  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command:
      sh -c '
        vault server -dev &
        export VAULT_ADDR="http://127.0.0.1:8200"
        export VAULT_TOKEN="root"
        vault secrets enable transit
        tail -f /dev/null
      '