services:
  psql-bank:
    image: postgres:17-alpine
    env_file:
      - build/psql/environment/bank.env
    networks:
      - bank-rest
  psql-authz:
    image: postgres:17-alpine
    env_file:
      - build/psql/environment/authz.env
    networks:
      - bank-rest
  redis:
    image: redis:8-alpine3.21
    networks:
      - bank-rest
  vault:
    image: vault:1.13.3
    env_file:
      - build/vault/environment/.env
    volumes:
      - ./build/vault/scripts/entrypoint.sh:/entrypoint.sh
    cap_add:
      - IPC_LOCK
    entrypoint: [ "sh", "/entrypoint.sh" ]
    networks:
      - bank-rest
  rabbit:
    container_name: rabbit
    build:
      context: .
      dockerfile: build/rabbit/Dockerfile
    env_file: build/rabbit/environment/.env
    ports:
      - "15672:15672"
    networks:
      - bank-rest
  bank-rest:
    build:
      context: .
      dockerfile: bank-rest/build/Dockerfile
    env_file:
      - build/psql/environment/bank.env
      - build/vault/environment/.env
      - build/rabbit/environment/.env
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
      - psql-bank
      - vault
    networks:
      - bank-rest
  authz-rest:
    build:
      context: .
      dockerfile: authz-rest/build/Dockerfile
    env_file:
      - authz-rest/build/environment/.env
      - build/psql/environment/authz.env
      - build/vault/environment/.env
    ports:
      - "8081:8081"
    depends_on:
      - psql-authz
      - redis
    networks:
      - bank-rest

networks:
  bank-rest:
    external: false
    driver: bridge