spring:
  docker:
    compose:
      enabled: true
      file:
        - docker-compose.yml
  vault:
    port: 8200
    host: localhost
    uri: http://localhost:8200
    token: root
  liquibase:
    change-log: db/migration/db.changelog-master.yml
