services:
  redis:
    image: redis:8-alpine3.21
    ports:
      - "6379:6379"
  psql:
    image: postgres:17-alpine
    environment:
      - "POSTGRES_DB=developer"
      - "POSTGRES_USER=developer"
      - "POSTGRES_PASSWORD=developer"
    ports:
      - "5432:5432"
  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    env_file:
      - build/vault/environment/.env
    volumes:
      - ./build/vault/scripts/entrypoint.sh:/entrypoint.sh
    cap_add:
      - IPC_LOCK
    entrypoint: ["sh", "/entrypoint.sh"]

volumes:
  rabbitmq_data: