services:
  psql:
    image: postgres:17-alpine
    environment:
      - "POSTGRES_DB=developer"
      - "POSTGRES_USER=developer"
      - "POSTGRES_PASSWORD=developer"
    ports:
      - "5432:5432"
  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    env_file:
      - build/vault/environment/.env
    volumes:
      - ./build/vault/scripts/entrypoint.sh:/entrypoint.sh
    cap_add:
      - IPC_LOCK
    entrypoint: ["sh", "/entrypoint.sh"]
  rabbit:
    build:
      context: .
      dockerfile: build/rabbit/Dockerfile
    env_file: build/rabbit/environment/.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: