spring:
  docker:
    compose:
      enabled: true
      file:
        - bank-rest/docker-compose.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/v1/auth/.well-known.jwks
  vault:
    port: 8200
    host: localhost
    uri: http://localhost:8200
    token: root
  authz:
    uri: http://localhost:8081/api/v1/users
  liquibase:
    change-log: db/migration/db.changelog-master.yml
