#file: noinspection undefined
spring:
  application:
    name: bank-rest
  liquibase:
    change-log: db/migration/db.changelog-master.yml

server:
  port: 8080

vault:
  key:
    api:
      path: my-encryption-key
mq:
  exchange:
    transaction: transaction.exchange
  routing-key:
    transaction: transaction.created
  queue:
    transaction: transaction.created.queue