#file: noinspection undefined
spring:
  application:
    name: bank-rest
  liquibase:
    change-log: db/migration/db.changelog-master.yml
  custom:
    outbox:
      type:
        transaction: transaction_event
server:
  port: 8080

vault:
  key:
    api:
      path: my-encryption-key