spring:
  docker:
    compose:
      enabled: false
  devtools:
    add-properties: false
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://bank-rest:8080/api/v1/auth/.well-known/jwks
  vault:
    uri: ${VAULT_BASE_URL}
    token: ${VAULT_DEV_ROOT_TOKEN_ID}
  authz:
    uri: http://bank-rest:8080/api/v1/users
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
vault:
  uri: ${VAULT_BASE_URL}
  token: ${VAULT_DEV_ROOT_TOKEN_ID}
  jwt-sign-key:
    path: ${JWT_PATH_SIGN_KEY}

jwt:
  ttl:
    access: ${JWT_ACCESS_TTL_MINUTES}
    refresh: ${JWT_REFRESH_TTL_HOURS}
  keySize: 2048
  privateKeyPath: ${JWT_SIGN_PRIVATE_KEY_PATH}
  publicKeyPath: ${JWT_SIGN_PUBLIC_KEY_PATH}
  kidPath: ${JWT_SIGN_KID_PATH}