#file: noinspection undefined
spring:
  application:
    name: bank-rest

server:
  port: 8080

vault:
  key:
    api:
      path: my-encryption-key

##
## application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.