services:
  psql:
    image: postgres:17-alpine
    environment:
      - "POSTGRES_DB=developer"
      - "POSTGRES_USER=developer"
      - "POSTGRES_PASSWORD=developer"
    ports:
      - "5433:5432"
  redis:
    image: redis:8-alpine3.21
    ports:
      - "6379:6379"
