openapi: 3.1.0
info:
  title: BANK-REST
  description: JWT Access Token authentication. First login and you will receive token pair.
  contact:
    name: Egor Gunter
    email: zerrrox05@mail.ru
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Generated server url
security:
  - Bearer Authentication: []
paths:
  /api/v1/profile/cards/{id}/block:
    put:
      tags:
        - profile-controller
      operationId: blockCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/cards/{id}:
    get:
      tags:
        - cards-controller
      operationId: readCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    put:
      tags:
        - cards-controller
      operationId: updateCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardUpdatePayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    delete:
      tags:
        - cards-controller
      operationId: deleteCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/balances/{id}:
    get:
      tags:
        - balance-controller
      operationId: readBalance
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    put:
      tags:
        - balance-controller
      operationId: updateBalance
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceUpdatePayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/transactions:
    get:
      tags:
        - transactions-controller
      operationId: readTransactions
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 5
        - name: filter
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/TransactionFilter"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    post:
      tags:
        - transactions-controller
      operationId: createTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionPayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/profile/transactions:
    get:
      tags:
        - profile-controller
      operationId: readTransactions_1
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 5
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    post:
      tags:
        - profile-controller
      operationId: createTransaction_1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionPayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/cards:
    get:
      tags:
        - cards-controller
      operationId: getCards
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 5
        - name: filter
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/CardFilter"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    post:
      tags:
        - cards-controller
      operationId: createCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardPayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/transactions/{id}:
    get:
      tags:
        - transactions-controller
      operationId: readTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/profile/cards:
    get:
      tags:
        - profile-controller
      operationId: getUserCards
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 5
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/profile/cards/{id}:
    get:
      tags:
        - profile-controller
      operationId: getUserCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
  /api/v1/users/{id}:
    get:
      tags: [ users-controller ]
      operationId: readUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    put:
      tags: [ users-controller ]
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdatePayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    delete:
      tags: [ users-controller ]
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/roles/{id}:
    get:
      tags: [ roles-controller ]
      operationId: readRole
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    put:
      tags: [ roles-controller ]
      operationId: updateRole
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleUpdatePayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    delete:
      tags: [ roles-controller ]
      operationId: deleteRole
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/users:
    get:
      tags: [ users-controller ]
      operationId: getRoles
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            format: int32
            default: 5
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    post:
      tags: [ users-controller ]
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/roles:
    get:
      tags: [ roles-controller ]
      operationId: getRoles_1
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            format: int32
            default: 5
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
    post:
      tags: [ roles-controller ]
      operationId: createRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RolePayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/auth/register:
    post:
      tags: [ authentication-controller ]
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/auth/refresh:
    post:
      tags: [ authentication-controller ]
      operationId: refreshAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenPayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/auth/logout:
    post:
      tags: [ authentication-controller ]
      operationId: logoutUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenPayload"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/auth/login:
    post:
      tags: [ authentication-controller ]
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/profile:
    get:
      tags: [ profile-controller ]
      operationId: getProfile
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object

  /api/v1/auth/.well-known/jwks:
    get:
      tags: [ authentication-controller ]
      operationId: jwksEndpoint
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: object
components:
  schemas:
    CardUpdatePayload:
      type: object
      properties:
        status:
          type: string
          enum: [active, blocked, expired]
        expirationDate:
          type: string
          format: date
      required: [status]
    BalanceUpdatePayload:
      type: object
      properties:
        value:
          type: number
        blocked:
          type: boolean
    TransactionPayload:
      type: object
      properties:
        senderCardId:
          type: string
          format: uuid
        receiverCardId:
          type: string
          format: uuid
        amount:
          type: number
      required: [amount, receiverCardId, senderCardId]
    CardPayload:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        number:
          type: string
          minLength: 1
          pattern: "^\d{16}$"
        expirationDate:
          type: string
          format: date
        brand:
          type: string
          maxLength: 32
          minLength: 0
      required: [brand, number, userId]
    TransactionFilter:
      type: object
      properties:
        cardIds:
          type: array
          items:
            type: string
            format: uuid
        senderCardId:
          type: string
          format: uuid
        receiverCardId:
          type: string
          format: uuid
        amount:
          type: number
    CardFilter:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        status:
          type: string
          enum: [active, blocked, expired]
        amountDesc:
          type: boolean
        amount:
          type: number
        expirationDate:
          type: string
          format: date-time
        dateDesc:
          type: boolean
    UserUpdatePayload:
      type: object
      required: [ roleIds, username ]
      properties:
        username:
          type: string
          minLength: 6
          maxLength: 256
        roleIds:
          type: array
          minItems: 1
          items:
            type: integer
            format: int32
    RoleUpdatePayload:
      type: object
      required: [ name ]
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 32
    UserPayload:
      type: object
      required: [ password, username ]
      properties:
        username:
          type: string
          minLength: 6
          maxLength: 256
        password:
          type: string
          minLength: 1
        roleIds:
          type: array
          items:
            type: integer
            format: int32
    RolePayload:
      type: object
      required: [ name ]
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 32
    RegisterRequest:
      type: object
      required: [ password, username ]
      properties:
        username:
          type: string
          minLength: 6
          maxLength: 256
        password:
          type: string
          minLength: 1
    RefreshTokenPayload:
      type: object
      required: [ value ]
      properties:
        value:
          type: string
    LoginRequest:
      type: object
      required: [ password, username ]
      properties:
        username:
          type: string
        password:
          type: string

  securitySchemes:
    Bearer Authentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
